#!/bin/bash

echo "=========================================="
echo "TEST SENARYOSU 2"
echo "=========================================="
echo "Tolerance Level: 3"
echo "Member Sayısı: 6 + 1 Lider"
echo "Test Mesaj Sayısı: 9000"
echo ""
echo "Bu test şunları kontrol eder:"
echo "  - 9000 mesajın dengeli dağılımı"
echo "  - Her mesajın 3 üyede saklanması"
echo "  - İki üye çökerse mesajların alınabilmesi"
echo ""
echo "ADIM 1: tolerance.conf dosyasını düzenleyin:"
echo "  tolerance=3"
echo ""
echo "ADIM 2: Ayrı terminallerde şu komutları çalıştırın:"
echo ""
echo "Terminal 1 (Lider):"
echo "  ./run-leader.sh"
echo ""
echo "Terminal 2-7 (Üyeler):"
echo "  ./run-member.sh 1 50052"
echo "  ./run-member.sh 2 50053"
echo "  ./run-member.sh 3 50054"
echo "  ./run-member.sh 4 50055"
echo "  ./run-member.sh 5 50056"
echo "  ./run-member.sh 6 50057"
echo ""
echo "ADIM 3: Tüm sunucular başladıktan sonra test istemcisini başlatın:"
echo "  mvn exec:java -Dexec.mainClass=\"com.hatokuse.Client\" -Dexec.args=\"localhost 8080 --test 9000\"
echo ""
echo "=========================================="
