#!/bin/bash

echo "=========================================="
echo "TEST SENARYOSU 1"
echo "=========================================="
echo "Tolerance Level: 2"
echo "Member Sayısı: 4 + 1 Lider"
echo "Test Mesaj Sayısı: 1000"
echo ""
echo "Bu test şunları kontrol eder:"
echo "  - 1000 mesajın dengeli dağılımı"
echo "  - Her mesajın 2 üyede saklanması"
echo "  - Bir üye çökerse mesajların alınabilmesi"
echo ""
echo "Lütfen ayrı terminallerde şu komutları çalıştırın:"
echo ""
echo "Terminal 1 (Lider):"
echo "  ./run-leader.sh"
echo ""
echo "Terminal 2-5 (Üyeler):"
echo "  ./run-member.sh 1 50052"
echo "  ./run-member.sh 2 50053"
echo "  ./run-member.sh 3 50054"
echo "  ./run-member.sh 4 50055"
echo ""
echo "Tüm sunucular başladıktan sonra test istemcisini başlatın:"
echo "  mvn exec:java -Dexec.mainClass=\"com.hatokuse.Client\" -Dexec.args=\"localhost 8080 --test 1000\"
echo ""
echo "=========================================="
